version: '3'
services:
  db:
    image: mysql:5.7.25
    env_file: .env
    volumes:
      - ./mysql-data:/var/lib/mysql
  web:
    build: .
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db